name: webide
version: 0.0.1
authors:
- roberthartung
- tejainece
homepage: https://github.com/webide/webide
dependencies:
  browser: any
  html_import: any
  observe: any
  polymer: 0.10.0-pre.10
transformers:
- polymer:
    entry_points:
    - web/experiments/layout/main.html